import type { FormEvent } from 'react'
import type { Project } from '../../domains/project/types'
import type { WorkspaceMembership } from '../../domains/workspace/types'

type ProjectsPanelProps = { activeWorkspace: WorkspaceMembership | undefined; activeProject: Project | undefined; projects: Project[]; isLoadingProjects: boolean; onReload: () => void; onSelectProject: (projectId: string) => void }
const panel = 'grid gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm'
const input = 'w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-brand-600 focus:ring-4 focus:ring-brand-100'
export function ProjectsPanel({ activeWorkspace, activeProject, projects, isLoadingProjects, onReload, onSelectProject }: ProjectsPanelProps) { return <article className={panel}><header className="flex items-center justify-between gap-3"><span className="text-xs font-extrabold uppercase tracking-wide text-brand-600">Projects</span><button className="rounded-lg px-2 py-1.5 text-sm font-bold text-brand-700 hover:bg-brand-50 disabled:cursor-wait disabled:opacity-55" type="button" onClick={onReload} disabled={!activeWorkspace || isLoadingProjects}>{isLoadingProjects ? 'Loading' : 'Reload'}</button></header><div className="grid gap-5 md:grid-cols-[minmax(13.75rem,.85fr)_minmax(0,1.15fr)]"><div className="grid content-start gap-2" aria-label="Projects">{projects.map((project) => <button key={project.id} className={`grid gap-1 rounded-lg border px-3 py-2.5 text-left ${project.id === activeProject?.id ? 'border-brand-600 bg-brand-50' : 'border-slate-200 hover:bg-slate-50'}`} type="button" onClick={() => onSelectProject(project.id)}><span className="font-bold text-ink">{project.name}</span><small className="text-xs text-muted">{new Date(project.created_at).toLocaleDateString()}</small></button>)}{projects.length === 0 ? <p className="text-sm text-muted">No projects found.</p> : null}</div><div className="min-h-37 border-t border-slate-200 pt-4 md:border-l md:border-t-0 md:pl-5 md:pt-0">{activeProject ? <><span className="text-xs font-extrabold uppercase tracking-wide text-brand-600">Project</span><h2 className="mt-2 text-lg font-bold text-ink">{activeProject.name}</h2><p className="mt-2 text-sm text-muted">{activeProject.description ?? 'No description'}</p></> : <p className="text-sm text-muted">No project selected.</p>}</div></div></article> }
type CreateProjectPanelProps = { activeWorkspace: WorkspaceMembership | undefined; projectName: string; projectDescription: string; isCreatingProject: boolean; onProjectNameChange: (value: string) => void; onProjectDescriptionChange: (value: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }
export function CreateProjectPanel({ activeWorkspace, projectName, projectDescription, isCreatingProject, onProjectNameChange, onProjectDescriptionChange, onSubmit }: CreateProjectPanelProps) { return <article className={panel}><span className="text-xs font-extrabold uppercase tracking-wide text-brand-600">New project</span><form className="grid gap-3" onSubmit={onSubmit}><label className="grid gap-1.5 text-sm font-bold text-slate-700">Name<input className={input} value={projectName} onChange={(event) => onProjectNameChange(event.target.value)} required /></label><label className="grid gap-1.5 text-sm font-bold text-slate-700">Description<textarea className={`${input} min-h-20 resize-y`} value={projectDescription} onChange={(event) => onProjectDescriptionChange(event.target.value)} rows={3} /></label><button className="min-h-10 rounded-lg bg-brand-600 px-4 text-sm font-extrabold text-white transition hover:bg-brand-700 disabled:cursor-wait disabled:opacity-60" type="submit" disabled={!activeWorkspace || isCreatingProject}>{isCreatingProject ? 'Creating' : 'Create project'}</button></form></article> }
