import { BrainCircuit, Check, CircleHelp, Eye, EyeOff, FileText, GitBranch, Home, LockKeyhole, Mail, Network, Plus, ShieldCheck, Sparkles, User, Users, Wand2, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { useState } from 'react'
import type { ReactNode } from 'react'

type AuthArtwork = 'lock' | 'profile' | 'mail' | 'question' | 'key' | 'home'
type AuthIconName = 'user' | 'mail' | 'lock' | 'eye' | 'home' | 'check' | 'plus' | 'help' | 'cube'

export function AuthFrame({ artwork, children }: { artwork: AuthArtwork; children: ReactNode }) {
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-4 sm:p-8"><section className="grid w-full max-w-6xl overflow-hidden rounded-3xl bg-white shadow-2xl lg:grid-cols-[minmax(0,1fr)_minmax(22rem,.9fr)]"><section className="order-2 p-6 sm:p-10 lg:order-1">{children}</section><AuthVisualPanel artwork={artwork} /></section></main>
}

function AuthVisualPanel({ artwork }: { artwork: AuthArtwork }) {
  const isProfile = artwork === 'profile'
  return <aside className="order-1 grid min-h-80 content-between bg-gradient-to-br from-brand-700 via-violet-700 to-slate-950 p-6 text-white sm:p-10 lg:order-2" aria-label="SRS Platform"><div><div className="flex items-center gap-2 text-lg font-bold"><img className="size-8 rounded-lg bg-white object-contain p-1" src="/srs-gen-platform-log.png" alt="" aria-hidden="true" />SRS Platform</div>{isProfile ? <span className="mt-8 inline-flex items-center gap-1 rounded-full bg-white/10 px-3 py-1 text-xs font-bold tracking-wide"><Sparkles size={14} />AI-POWERED</span> : null}</div><section className="my-8 grid gap-3" aria-hidden="true"><article className="rounded-xl bg-white/10 p-4 backdrop-blur"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-white/15"><Wand2 size={17} /></span><strong>AI Generation</strong></div><p className="mt-3 text-sm text-white/75">Generating SRS document...</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/15"><i className="block h-full w-[72%] rounded-full bg-white" /></div></article><div className="grid grid-cols-2 gap-3"><PreviewCard icon={FileText} label="SRS Document" value="v1.2" /><PreviewCard icon={GitBranch} label="Requirements" value="24" /><PreviewCard icon={Network} label="Diagrams" value="88" /></div></section><div><h2 className="text-2xl font-bold leading-tight">{isProfile ? 'Write better SRS. Faster with AI.' : 'All your SRS work, smarter with AI'}</h2><p className="mt-3 text-sm leading-6 text-white/75">Create, collaborate, and manage SRS documents, diagrams, and requirements in one intelligent platform.</p><div className="mt-6 grid grid-cols-2 gap-3">{(isProfile ? signupFeatures : loginFeatures).map((feature) => <FeatureChip {...feature} key={feature.title} />)}</div></div></aside>
}

function PreviewCard({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) { return <article className="grid gap-2 rounded-xl bg-white/10 p-3"><Icon size={18} /><strong className="text-lg">{value}</strong><small className="text-xs text-white/70">{label}</small></article> }
const loginFeatures = [{ icon: BrainCircuit, title: 'AI-Powered', label: 'Generation' }, { icon: Network, title: 'Smart', label: 'Diagrams' }, { icon: ShieldCheck, title: 'Version', label: 'Control' }, { icon: Users, title: 'Team', label: 'Collaboration' }]
const signupFeatures = [{ icon: BrainCircuit, title: 'AI Writing', label: 'Generate and refine SRS content' }, { icon: Network, title: 'Smart Diagrams', label: 'Auto-generate UML diagrams' }, { icon: Users, title: 'Collaboration', label: 'Work together seamlessly' }, { icon: ShieldCheck, title: 'Enterprise', label: 'Secure and scalable' }]
function FeatureChip({ icon: Icon, title, label }: { icon: LucideIcon; title: string; label: string }) { return <span className="grid gap-1 rounded-lg bg-white/10 p-2.5"><Icon size={18} /><strong className="text-xs">{title}</strong><small className="text-[10px] leading-4 text-white/70">{label}</small></span> }

export function AuthField({ label, icon, type = 'text', value, placeholder, autoComplete, inputMode, required, minLength, error, onChange }: { label: string; icon: AuthIconName; type?: string; value: string; placeholder: string; autoComplete?: string; inputMode?: 'email' | 'numeric'; required?: boolean; minLength?: number; error?: string; onChange: (value: string) => void }) {
  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const isPasswordField = type === 'password'
  return <label className="grid gap-1.5"><span className="text-sm font-semibold text-slate-700">{label}</span><span className={`flex items-center gap-2 rounded-lg border bg-white px-3 py-2.5 transition ${error ? 'border-rose-400' : 'border-slate-300 focus-within:border-brand-500 focus-within:ring-3 focus-within:ring-brand-100'}`}><span className="text-slate-400"><AuthIcon name={icon} /></span><input className="min-w-0 flex-1 text-sm text-slate-900 outline-none" aria-invalid={Boolean(error)} autoComplete={autoComplete} inputMode={inputMode} minLength={minLength} placeholder={placeholder} required={required} type={isPasswordField && isPasswordVisible ? 'text' : type} value={value} onChange={(event) => onChange(event.target.value)} />{isPasswordField ? <button className="text-slate-400 hover:text-slate-700" type="button" aria-label={isPasswordVisible ? 'Hide password' : 'Show password'} onClick={(event) => { event.preventDefault(); setIsPasswordVisible((visible) => !visible) }}>{isPasswordVisible ? <EyeOff size={18} /> : <Eye size={18} />}</button> : null}</span>{error ? <small className="text-xs font-medium text-rose-600">{error}</small> : null}</label>
}

const authIcons: Record<AuthIconName, LucideIcon> = { check: Check, cube: X, eye: Eye, help: CircleHelp, home: Home, lock: LockKeyhole, mail: Mail, plus: Plus, user: User }
export function AuthIcon({ name }: { name: AuthIconName }) { const Icon = authIcons[name]; return <Icon size={18} aria-hidden="true" /> }
export function AuthLinkButton({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="text-sm font-bold text-brand-600 hover:text-brand-700" type="button" onClick={onClick}>{children}</button> }
export function AuthPanelHeader({ title, subtitle }: { title: string; subtitle: string }) { return <header className="mb-7"><h1 className="text-3xl font-bold tracking-tight text-slate-950">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p></header> }
